/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_tomahawk_XFileDialog */

#ifndef _Included_net_tomahawk_XFileDialog
#define _Included_net_tomahawk_XFileDialog
#ifdef __cplusplus
extern "C" {
#endif
#undef net_tomahawk_XFileDialog_LOAD
#define net_tomahawk_XFileDialog_LOAD 0L
#undef net_tomahawk_XFileDialog_SAVE
#define net_tomahawk_XFileDialog_SAVE 1L
/*
 * Class:     net_tomahawk_XFileDialog
 * Method:    nativeWindowsInitialize
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_tomahawk_XFileDialog_nativeWindowsInitialize
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_tomahawk_XFileDialog
 * Method:    nativeWindowsFileDialog
 * Signature: (ILjava/awt/Window;Ljava/lang/String;ZZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_tomahawk_XFileDialog_nativeWindowsFileDialog
  (JNIEnv *, jobject, jint, jobject, jstring, jboolean, jboolean, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
